apiVersion: v1
kind: Secret
metadata:
  name: credentials # Secret will be referenceable by the name 'credentials'
type: Opaque
stringData:
  secret-key: {{SECRET_KEY}} # {{SECRET_KEY}} will be substituted for our secret key
