apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
  - name: todo
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata: 
  name: todo
  labels: 
    app: todo
spec: 
  containers:
  - name: todo 
    image: htrvolker/todo-app:sqlite 
    env: 
    - name: SECRET_KEY # The app is designed to get the secret key 
      valueFrom: # from an environment variable 
        secretKeyRef: 
          name: credentials # Referencing the Secret's name 
          key: secret-key # Referencing the key/value pair under the Secret's stringData property
